### ISSUE TITLE
TypeError: Converting circular structure to JSON

### ISSUE THREAD

**Issue by jenschude** [mulesoft-labs/raml-json-enhance-node#6]
I'm using raml-json-enhance-node at version 0.3.2

With the following expansion script:

```javascript
const {RamlJsonGenerator} = require('raml-json-enhance-node');

process.stdout.write("\n# Converting RAML to enhanced JSON ...");

const enhancer = new RamlJsonGenerator('./test.raml', {
    output: './test.json',
    prettyPrint: true
});
enhancer.generate()
    .then(function(json) {
        process.stdout.write(" \x1b[32mdone\x1b[0m.\n");
    })
    .catch((cause) => {
        process.stdout.write(" \x1b[31mfailed\x1b[0m.\n");
        console.error(cause);
    });
```

and the used test.raml file

```raml
#%RAML 1.0
title: Example API
types:
    CategoryReference:
        type: object
        properties:
            id: string
            obj: Category
    Category:
        type: object
        properties:
            name:
                type: string
            parent?:
                type: CategoryReference
/{id}:
  post:
    responses:
      201:
        body:
          application/json:
            type: Category
```

I get following type error

```
TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at Promise (node_modules/raml-json-enhance-node/lib/json-generator.js:104:25)
    at new Promise (<anonymous>)
    at JsonGenerator.save (node_modules/raml-json-enhance-node/lib/json-generator.js:101:12)
    at parse.then.then (node_modules/raml-json-enhance-node/lib/json-generator.js:61:26)
    at <anonymous>
```

**Comment by jenschude** [comment]
The issue is maybe related to:

https://github.com/raml-org/datatype-expansion/issues/51

**Comment by jenschude** [comment]
Also the following raml without an intermediate object is not working:

```raml
#%RAML 1.0
title: Example API
types:
    Category:
        type: object
        properties:
            name:
                type: string
            parent?:
                type: Category
/{id}:
  get:
    queryParameters:
      sort:
        enum: [username, name]
    responses:
      200:
        body:
          application/json:
            type: Category
```

**Comment by jarrodek** [comment]
Thank you for issue report. Very sorry for taking so long. 
This will be fixed when this PR is merged: https://github.com/mulesoft-labs/raml-json-enhance-node/pull/7
